# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('rosvehcomm', ['core', 'wifi', 'applications', 'mobility','internet', 'config-store','stats', 'applications', 'fd-net-device','netanim'])
    module.source = [
        'model/rosvehicule.cc',
		'model/rosvehsync.cc',
    	'helper/rosvehsync-helper.cc',
		'helper/rosvehicule-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('rosvehcomm')
    module_test.source = [
        'test/rosvehcomm-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/rosvehcomm-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'rosvehcomm'
    headers.source = [
        'model/rosvehicule.h',
		'model/rosvehsync.h',
    	'helper/rosvehsync-helper.h',
		'helper/rosvehicule-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()


